### PR TITLE
Use futures and tokio to send activities

### LINKED ISSUE #252: Improve ActivityPub delivery
When sending activities to a lot of other inboxes, we currently have two problems:

- some of them timeout, but blocks the delivery for a long time
- if one request fails, the following ones are never sent

We should try to see if we can make each request asynchronously, and make handle errors properly to avoid to stop the other tasks.

Plume version (and/or commit): 0.2.0

### PR DESCRIPTION
**Pull request by BaptisteGelez**
Fixes #252

Publishing an article and having it federated to the whole fediverse only takes a few seconds now (instead of minutes before, on big Plume instances connected to many other ones).

### CODE REVIEW

File: plume-common/src/activity_pub/mod.rs [hunk 1]
```diff
@@ -129,38 +130,38 @@ where
         .sign(sender)
         .expect("activity_pub::broadcast: signature error");
 
+    let mut rt = tokio::runtime::current_thread::Runtime::new().expect("new rt");
+    let client = ClientBuilder::new()
+        .connect_timeout(std::time::Duration::from_secs(5))
+        .build()
+        .expect("Can't build client");
     for inbox in boxes {
         // TODO: run it in Sidekiq or something like that
```
Comment (igalic) [inline plume-common/src/activity_pub/mod.rs]: is this comment still relevant?

File: plume-common/src/activity_pub/mod.rs [hunk 2]
```diff
@@ -129,38 +130,38 @@ where
         .sign(sender)
         .expect("activity_pub::broadcast: signature error");
 
+    let mut rt = tokio::runtime::current_thread::Runtime::new().expect("new rt");
```
Comment (igalic) [inline plume-common/src/activity_pub/mod.rs]: if this fails, we panic with "new rt".??

File: plume-common/src/activity_pub/mod.rs [hunk 3]
```diff
@@ -129,38 +130,38 @@ where
...
-                } else {
-                    println!("Error while reading response")
-                }
-            }
-            Err(e) => println!("Error while sending to inbox ({:?})", e),
-        }
+                r.into_body().concat2()
+            })
+            .map(|response| {
+                println!("Response: \"{:?}\"\n\n", response)
```
Comment (igalic) [inline plume-common/src/activity_pub/mod.rs]: i think we should talk about our logging strategy sometime 😅

File: plume-common/src/activity_pub/mod.rs (hunk 1 above)
Comment (BaptisteGelez) [reply plume-common/src/activity_pub/mod.rs]: Not really, but it is for the background jobs in general, for the moment we just spawn them in a separate thread and that's it. I will remove it and create a more general issue.

File: plume-common/src/activity_pub/mod.rs (hunk 2 above)
Comment (BaptisteGelez) [reply plume-common/src/activity_pub/mod.rs]: Hum… yes, I could probably change that. To be honest I copied this line from reqwest examples without really thinking about it :sweat_smile:

File: plume-common/src/activity_pub/mod.rs (hunk 3 above)
Comment (BaptisteGelez) [reply plume-common/src/activity_pub/mod.rs]: Indeed, we should probably use `log` and `env_logger` or something like that. Should I create an issue?

File: plume-common/src/activity_pub/mod.rs [hunk 4]
```diff
@@ -129,38 +130,36 @@ where
...
+                .headers(headers.clone())
+                .header(
+                    "Signature",
+                    request::signature(sender, &headers)
+                        .expect("activity_pub::broadcast: request signature error"),
+                )
+                .body(body)
+                .send()
+                .and_then(move |r| {
+                    println!("Successfully sent activity to inbox ({})", inbox);
```
Comment (fdb-hiroshima) [inline plume-common/src/activity_pub/mod.rs]: I think this print should be done in the map just under, otherwise output could get mixed quickly, making both logs useless

File: plume-common/src/activity_pub/mod.rs [hunk 5]
```diff
@@ -129,38 +130,36 @@ where
...
+                    r.into_body().concat2()
+                })
+                .map(|response| println!("Response: \"{:?}\"\n\n", response))
+                .map_err(|e| println!("Error while sending to inbox ({:?})", e)),
```
Comment (fdb-hiroshima) [inline plume-common/src/activity_pub/mod.rs]: (what is that comma for?)

Comment (BaptisteGelez) [reply plume-common/src/activity_pub/mod.rs]: (no idea, I will remove it)

Comment (BaptisteGelez) [reply plume-common/src/activity_pub/mod.rs]: Actually, it is added by cargo-fmt, because this whole expression is the argument of a function.

Comment (fdb-hiroshima) [reply plume-common/src/activity_pub/mod.rs]: okay...
