### PR TITLE
Display error message when signin up with unmatching password

### LINKED ISSUE #329: Registering new account with invalid confirmation password fail silently
While registering a new account, providing two different password fail as supposed to, but it don't give any feedback to the user on why he is back to registration page.
Expected behavior : show a message indicating a password mismatch

Plume version (and/or commit): 74c398d60c9bfeb6799023bb2140c05daf0ae5ff

### PR DESCRIPTION
**Pull request by fdb-hiroshima**
Fix #329

### CODE REVIEW

File: templates/users/new.rs.html [hunk 1]
```diff
@@ -13,6 +14,9 @@ <h1>@i18n!(ctx.1, "Create an account")</h1>
             @input!(ctx.1, username (text), "Username", form, errors.clone(), "minlenght=\"1\"")
             @input!(ctx.1, email (text), "Email", form, errors.clone())
             @input!(ctx.1, password (password), "Password", form, errors.clone(), "minlenght=\"8\"")
+            @if let Some(ValidationErrorsKind::Field(errs)) = errors.clone().errors().get("__all__") {
```
Comment (BaptisteGelez) [inline templates/users/new.rs.html]: Does this actually work? :open_mouth:

Comment (fdb-hiroshima) [reply templates/users/new.rs.html]: yes, my true love dbg! told me the way
